//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Send {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SendSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SendSettings defaultInstance = ((SendSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SendSettings())));
        
        public static SendSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Send\' and @index=\'0\']")]
        public string Send {
            get {
                return ((string)(this["Send"]));
            }
            set {
                this["Send"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Kehinde Adeoya  \' and @index=\'0\']")]
        public string SendToSelfSelect {
            get {
                return ((string)(this["SendToSelfSelect"]));
            }
            set {
                this["SendToSelfSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter Amount\' and @index=\'1\']")]
        public string SendAmount {
            get {
                return ((string)(this["SendAmount"]));
            }
            set {
                this["SendAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter Remarks\' and @index=\'1\']")]
        public string SendRemarks {
            get {
                return ((string)(this["SendRemarks"]));
            }
            set {
                this["SendRemarks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'NEXT\' and @index=\'0\']")]
        public string SendNextButton {
            get {
                return ((string)(this["SendNextButton"]));
            }
            set {
                this["SendNextButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Next\' and @index=\'0\']")]
        public string SendSummaryButton {
            get {
                return ((string)(this["SendSummaryButton"]));
            }
            set {
                this["SendSummaryButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string CardPAN {
            get {
                return ((string)(this["CardPAN"]));
            }
            set {
                this["CardPAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'2\' and @index=\'0\']")]
        public string CardPIN_1 {
            get {
                return ((string)(this["CardPIN_1"]));
            }
            set {
                this["CardPIN_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'0\' and @index=\'0\']")]
        public string CardPIN_2 {
            get {
                return ((string)(this["CardPIN_2"]));
            }
            set {
                this["CardPIN_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'1\' and @index=\'0\']")]
        public string CardPIN_3 {
            get {
                return ((string)(this["CardPIN_3"]));
            }
            set {
                this["CardPIN_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'1\' and @index=\'0\']")]
        public string CardPIN_4 {
            get {
                return ((string)(this["CardPIN_4"]));
            }
            set {
                this["CardPIN_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.LinearLayout[@index=\'1\']")]
        public string ConfirmPassOrFail {
            get {
                return ((string)(this["ConfirmPassOrFail"]));
            }
            set {
                this["ConfirmPassOrFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@content-desc=\'Zone Send GoLive\']")]
        public string InsideSend {
            get {
                return ((string)(this["InsideSend"]));
            }
            set {
                this["InsideSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Retry\' and @index=\'1\']")]
        public string FailedRetry {
            get {
                return ((string)(this["FailedRetry"]));
            }
            set {
                this["FailedRetry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Replay\' and @index=\'1\']")]
        public string PassedReplay {
            get {
                return ((string)(this["PassedReplay"]));
            }
            set {
                this["PassedReplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string PassFeedback {
            get {
                return ((string)(this["PassFeedback"]));
            }
            set {
                this["PassFeedback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/label_full_name")]
        public string LoggedInUser {
            get {
                return ((string)(this["LoggedInUser"]));
            }
            set {
                this["LoggedInUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/name")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView")]
        public string SummaryPageFields {
            get {
                return ((string)(this["SummaryPageFields"]));
            }
            set {
                this["SummaryPageFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView")]
        public string CardPINPad {
            get {
                return ((string)(this["CardPINPad"]));
            }
            set {
                this["CardPINPad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\"")]
        public string CardPassedValue {
            get {
                return ((string)(this["CardPassedValue"]));
            }
            set {
                this["CardPassedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/card_indicator")]
        public string NumberOfCards {
            get {
                return ((string)(this["NumberOfCards"]));
            }
            set {
                this["NumberOfCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'0\']")]
        public string CardImage {
            get {
                return ((string)(this["CardImage"]));
            }
            set {
                this["CardImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Add Card\' and @index=\'0\']")]
        public string AddCardButton {
            get {
                return ((string)(this["AddCardButton"]));
            }
            set {
                this["AddCardButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string CardDigits {
            get {
                return ((string)(this["CardDigits"]));
            }
            set {
                this["CardDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'1\']")]
        public string BeneficiaryButton_1 {
            get {
                return ((string)(this["BeneficiaryButton_1"]));
            }
            set {
                this["BeneficiaryButton_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Account Number\' and @index=\'0\']")]
        public string BeneficiaryButton_2 {
            get {
                return ((string)(this["BeneficiaryButton_2"]));
            }
            set {
                this["BeneficiaryButton_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter Account Number\' and @index=\'1\']")]
        public string BeneficiaryAccount {
            get {
                return ((string)(this["BeneficiaryAccount"]));
            }
            set {
                this["BeneficiaryAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string BeneficiaryBank {
            get {
                return ((string)(this["BeneficiaryBank"]));
            }
            set {
                this["BeneficiaryBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Proceed\' and @index=\'2\']")]
        public string BeneficiaryProceedButton {
            get {
                return ((string)(this["BeneficiaryProceedButton"]));
            }
            set {
                this["BeneficiaryProceedButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string BeneficiarySummaryPage {
            get {
                return ((string)(this["BeneficiarySummaryPage"]));
            }
            set {
                this["BeneficiarySummaryPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'CONFIRM\' and @index=\'0\']")]
        public string BeneficiaryConfirm {
            get {
                return ((string)(this["BeneficiaryConfirm"]));
            }
            set {
                this["BeneficiaryConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string BenficiarySummaryNameField {
            get {
                return ((string)(this["BenficiarySummaryNameField"]));
            }
            set {
                this["BenficiarySummaryNameField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string SendToZoneContact {
            get {
                return ((string)(this["SendToZoneContact"]));
            }
            set {
                this["SendToZoneContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/ic_action_search")]
        public string Search {
            get {
                return ((string)(this["Search"]));
            }
            set {
                this["Search"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@index=\'1\']")]
        public string SearchField {
            get {
                return ((string)(this["SearchField"]));
            }
            set {
                this["SearchField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@index=\'0\' and @text=\'Send\']")]
        public string SendQuickLaunch {
            get {
                return ((string)(this["SendQuickLaunch"]));
            }
            set {
                this["SendQuickLaunch"] = value;
            }
        }
    }
}
