//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Sidebar {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SidebarSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SidebarSettings defaultInstance = ((SidebarSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SidebarSettings())));
        
        public static SidebarSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Add Card\']")]
        public string AddCard {
            get {
                return ((string)(this["AddCard"]));
            }
            set {
                this["AddCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_card_number")]
        public string CardNumber {
            get {
                return ((string)(this["CardNumber"]));
            }
            set {
                this["CardNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/label_expiry_date")]
        public string ExpriyDate {
            get {
                return ((string)(this["ExpriyDate"]));
            }
            set {
                this["ExpriyDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_cvv")]
        public string CardCCV {
            get {
                return ((string)(this["CardCCV"]));
            }
            set {
                this["CardCCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_pin")]
        public string CardPIN {
            get {
                return ((string)(this["CardPIN"]));
            }
            set {
                this["CardPIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/btn_add")]
        public string AddCardButton {
            get {
                return ((string)(this["AddCardButton"]));
            }
            set {
                this["AddCardButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'06\']")]
        public string ExpiryMonth {
            get {
                return ((string)(this["ExpiryMonth"]));
            }
            set {
                this["ExpiryMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'1\' and @index=\'0\']")]
        public string ExpiryYear_1 {
            get {
                return ((string)(this["ExpiryYear_1"]));
            }
            set {
                this["ExpiryYear_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'9\' and @index=\'2\']")]
        public string ExpiryYear_2 {
            get {
                return ((string)(this["ExpiryYear_2"]));
            }
            set {
                this["ExpiryYear_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/done_button")]
        public string OKButton {
            get {
                return ((string)(this["OKButton"]));
            }
            set {
                this["OKButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'MM - YYYY\']")]
        public string ExpiryDatePick {
            get {
                return ((string)(this["ExpiryDatePick"]));
            }
            set {
                this["ExpiryDatePick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'My Cards\']")]
        public string MyCards {
            get {
                return ((string)(this["MyCards"]));
            }
            set {
                this["MyCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckBox[@text=\'Default Card\' and @index=\'2\']")]
        public string MakeCardDefault {
            get {
                return ((string)(this["MakeCardDefault"]));
            }
            set {
                this["MakeCardDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Remove Card\' and @index=\'3\']")]
        public string RemoveCard {
            get {
                return ((string)(this["RemoveCard"]));
            }
            set {
                this["RemoveCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Yes\']")]
        public string YesDefault {
            get {
                return ((string)(this["YesDefault"]));
            }
            set {
                this["YesDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Yes\']")]
        public string RemoveCardYes {
            get {
                return ((string)(this["RemoveCardYes"]));
            }
            set {
                this["RemoveCardYes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'No\']")]
        public string NoDefault {
            get {
                return ((string)(this["NoDefault"]));
            }
            set {
                this["NoDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'No\']")]
        public string NoRemove {
            get {
                return ((string)(this["NoRemove"]));
            }
            set {
                this["NoRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Report a Problem\' and @index=\'0\']")]
        public string ReportAProblem {
            get {
                return ((string)(this["ReportAProblem"]));
            }
            set {
                this["ReportAProblem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Subject\' and @index=\'1\']")]
        public string ReportSubject {
            get {
                return ((string)(this["ReportSubject"]));
            }
            set {
                this["ReportSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Describe your problem\' and @index=\'3\']")]
        public string ReportDescribe {
            get {
                return ((string)(this["ReportDescribe"]));
            }
            set {
                this["ReportDescribe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Submit\' and @index=\'4\']")]
        public string ReportSubmitButton {
            get {
                return ((string)(this["ReportSubmitButton"]));
            }
            set {
                this["ReportSubmitButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Rate us\' and @index=\'0\']")]
        public string RateUs {
            get {
                return ((string)(this["RateUs"]));
            }
            set {
                this["RateUs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'About Zone\' and @index=\'0\']")]
        public string AboutZone {
            get {
                return ((string)(this["AboutZone"]));
            }
            set {
                this["AboutZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Share\' and @index=\'0\']")]
        public string Share {
            get {
                return ((string)(this["Share"]));
            }
            set {
                this["Share"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Help\' and @index=\'0\']")]
        public string Help {
            get {
                return ((string)(this["Help"]));
            }
            set {
                this["Help"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Log Out\' and @index=\'0\']")]
        public string LogOut {
            get {
                return ((string)(this["LogOut"]));
            }
            set {
                this["LogOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Messages\' and @index=\'1\']")]
        public string Messages {
            get {
                return ((string)(this["Messages"]));
            }
            set {
                this["Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Messenger\' and @index=\'1\']")]
        public string Messenger {
            get {
                return ((string)(this["Messenger"]));
            }
            set {
                this["Messenger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'WhatsApp\' and @index=\'1\']")]
        public string WhatsApp {
            get {
                return ((string)(this["WhatsApp"]));
            }
            set {
                this["WhatsApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Settings\' and @index=\'0\']")]
        public string AccountSettings {
            get {
                return ((string)(this["AccountSettings"]));
            }
            set {
                this["AccountSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Tap To Select a Network\' and @index=\'1\']")]
        public string SelectNetwork {
            get {
                return ((string)(this["SelectNetwork"]));
            }
            set {
                this["SelectNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Recharge Amount\' and @index=\'0\']")]
        public string RechargeAmount {
            get {
                return ((string)(this["RechargeAmount"]));
            }
            set {
                this["RechargeAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Account Details (Tap to Change)\' and @index=\'0\']" +
            "")]
        public string AccountDetails {
            get {
                return ((string)(this["AccountDetails"]));
            }
            set {
                this["AccountDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("android:id/checkbox")]
        public string QuickLaunch {
            get {
                return ((string)(this["QuickLaunch"]));
            }
            set {
                this["QuickLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Airtel\' and @index=\'2\']")]
        public string NetworkSelected {
            get {
                return ((string)(this["NetworkSelected"]));
            }
            set {
                this["NetworkSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@index=\'0\']")]
        public string TypeAmount {
            get {
                return ((string)(this["TypeAmount"]));
            }
            set {
                this["TypeAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'OK\' and @index=\'1\']")]
        public string TypeAmountOKButton {
            get {
                return ((string)(this["TypeAmountOKButton"]));
            }
            set {
                this["TypeAmountOKButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("android.widget.Button[@text=\'Cancel\' and @index=\'0\']")]
        public string TypeAmountCancelButton {
            get {
                return ((string)(this["TypeAmountCancelButton"]));
            }
            set {
                this["TypeAmountCancelButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.view.View[@index=\'2\']")]
        public string DeviceBackButton {
            get {
                return ((string)(this["DeviceBackButton"]));
            }
            set {
                this["DeviceBackButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'0\']")]
        public string RateUsValidate {
            get {
                return ((string)(this["RateUsValidate"]));
            }
            set {
                this["RateUsValidate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Facebook\' and @index=\'0\']")]
        public string AboutUsValidate {
            get {
                return ((string)(this["AboutUsValidate"]));
            }
            set {
                this["AboutUsValidate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Help\' and @index=\'1\']")]
        public string HelpValidate {
            get {
                return ((string)(this["HelpValidate"]));
            }
            set {
                this["HelpValidate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Network Operator\' and @index=\'0\']")]
        public string NetworkOperator {
            get {
                return ((string)(this["NetworkOperator"]));
            }
            set {
                this["NetworkOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Don\'t send\' and @index=\'1\']")]
        public string MessageDontSendButton {
            get {
                return ((string)(this["MessageDontSendButton"]));
            }
            set {
                this["MessageDontSendButton"] = value;
            }
        }
    }
}
