//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Auth {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AuthExtended : global::System.Configuration.ApplicationSettingsBase {
        
        private static AuthExtended defaultInstance = ((AuthExtended)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AuthExtended())));
        
        public static AuthExtended Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.LinearLayout[@index=\'0\']")]
        public string LInearLayout {
            get {
                return ((string)(this["LInearLayout"]));
            }
            set {
                this["LInearLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/dob")]
        public string DateOfBirth {
            get {
                return ((string)(this["DateOfBirth"]));
            }
            set {
                this["DateOfBirth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.LinearLayout[@index=\'0\']")]
        public string LinearLayoutYear {
            get {
                return ((string)(this["LinearLayoutYear"]));
            }
            set {
                this["LinearLayoutYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/date_picker_year")]
        public string DatePickerYear {
            get {
                return ((string)(this["DatePickerYear"]));
            }
            set {
                this["DatePickerYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/addMoreAcct")]
        public string AddMoreAccount {
            get {
                return ((string)(this["AddMoreAccount"]));
            }
            set {
                this["AddMoreAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/input_beneficiary")]
        public string AccountNumber {
            get {
                return ((string)(this["AccountNumber"]));
            }
            set {
                this["AccountNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/bank_name")]
        public string BankName {
            get {
                return ((string)(this["BankName"]));
            }
            set {
                this["BankName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Ecobank\']")]
        public string SelectedBankName {
            get {
                return ((string)(this["SelectedBankName"]));
            }
            set {
                this["SelectedBankName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/action_send")]
        public string AddAccountButton {
            get {
                return ((string)(this["AddAccountButton"]));
            }
            set {
                this["AddAccountButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/done_button")]
        public string DoneButton {
            get {
                return ((string)(this["DoneButton"]));
            }
            set {
                this["DoneButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/selector_header")]
        public string SelectorHeader {
            get {
                return ((string)(this["SelectorHeader"]));
            }
            set {
                this["SelectorHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/setUp")]
        public string SetupButton {
            get {
                return ((string)(this["SetupButton"]));
            }
            set {
                this["SetupButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/detailsText")]
        public string ExistingUser {
            get {
                return ((string)(this["ExistingUser"]));
            }
            set {
                this["ExistingUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Continue\']")]
        public string ContinueButton {
            get {
                return ((string)(this["ContinueButton"]));
            }
            set {
                this["ContinueButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/have_an_acct")]
        public string LoginLink {
            get {
                return ((string)(this["LoginLink"]));
            }
            set {
                this["LoginLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Phone number\']")]
        public string LoginPhoneNumber {
            get {
                return ((string)(this["LoginPhoneNumber"]));
            }
            set {
                this["LoginPhoneNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/password")]
        public string LoginPassword {
            get {
                return ((string)(this["LoginPassword"]));
            }
            set {
                this["LoginPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/login")]
        public string LoginButton {
            get {
                return ((string)(this["LoginButton"]));
            }
            set {
                this["LoginButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageButton[@index=\'0\']")]
        public string SideBar {
            get {
                return ((string)(this["SideBar"]));
            }
            set {
                this["SideBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.CheckedTextView[@text=\'Change Password\']")]
        public string ChangePassword {
            get {
                return ((string)(this["ChangePassword"]));
            }
            set {
                this["ChangePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_old_password")]
        public string OldPassword {
            get {
                return ((string)(this["OldPassword"]));
            }
            set {
                this["OldPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_new_password")]
        public string NewPassword {
            get {
                return ((string)(this["NewPassword"]));
            }
            set {
                this["NewPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/text_confirm_password")]
        public string ConfirmNewPassword {
            get {
                return ((string)(this["ConfirmNewPassword"]));
            }
            set {
                this["ConfirmNewPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/btn_change")]
        public string SaveNewPassowrdButton {
            get {
                return ((string)(this["SaveNewPassowrdButton"]));
            }
            set {
                this["SaveNewPassowrdButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@index=\'0\']")]
        public string LoginPasswordField {
            get {
                return ((string)(this["LoginPasswordField"]));
            }
            set {
                this["LoginPasswordField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'I forgot My Password\']")]
        public string ForgotPasswordButton {
            get {
                return ((string)(this["ForgotPasswordButton"]));
            }
            set {
                this["ForgotPasswordButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Renter Password\']")]
        public string ReEnterPasswordButton {
            get {
                return ((string)(this["ReEnterPasswordButton"]));
            }
            set {
                this["ReEnterPasswordButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@index=\'0\']")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Ask for Money from Friends\' and @index=\'0\']")]
        public string AskSlide {
            get {
                return ((string)(this["AskSlide"]));
            }
            set {
                this["AskSlide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'0\']")]
        public string SlideIcons {
            get {
                return ((string)(this["SlideIcons"]));
            }
            set {
                this["SlideIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Pay for Goods with Ease\' and @index=\'0\']")]
        public string PaySlide {
            get {
                return ((string)(this["PaySlide"]));
            }
            set {
                this["PaySlide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Merchant Services\' and @index=\'0\']")]
        public string MerchantSlide {
            get {
                return ((string)(this["MerchantSlide"]));
            }
            set {
                this["MerchantSlide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Send Money to Friends\' and @index=\'0\']")]
        public string SendSlide {
            get {
                return ((string)(this["SendSlide"]));
            }
            set {
                this["SendSlide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/zone_ic")]
        public string ZoneIcon {
            get {
                return ((string)(this["ZoneIcon"]));
            }
            set {
                this["ZoneIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string LabelPresentOnPage {
            get {
                return ((string)(this["LabelPresentOnPage"]));
            }
            set {
                this["LabelPresentOnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Google\' and @index=\'0\']")]
        public string GoogleSignup {
            get {
                return ((string)(this["GoogleSignup"]));
            }
            set {
                this["GoogleSignup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Facebook\' and @index=\'2\']")]
        public string FacebookSignup {
            get {
                return ((string)(this["FacebookSignup"]));
            }
            set {
                this["FacebookSignup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'0\']")]
        public string ProfileImage {
            get {
                return ((string)(this["ProfileImage"]));
            }
            set {
                this["ProfileImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Camera\' and @index=\'1\']")]
        public string Camera {
            get {
                return ((string)(this["Camera"]));
            }
            set {
                this["Camera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Documents\' and @index=\'1\']")]
        public string Documents {
            get {
                return ((string)(this["Documents"]));
            }
            set {
                this["Documents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Gallery\' and @index=\'1\']")]
        public string Gallery {
            get {
                return ((string)(this["Gallery"]));
            }
            set {
                this["Gallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string SelectProfileImage {
            get {
                return ((string)(this["SelectProfileImage"]));
            }
            set {
                this["SelectProfileImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.view.View[@index=\'0\']")]
        public string SelectImage {
            get {
                return ((string)(this["SelectImage"]));
            }
            set {
                this["SelectImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string AccountEmail {
            get {
                return ((string)(this["AccountEmail"]));
            }
            set {
                this["AccountEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@index=\'1\' and @text=\'Allow\']")]
        public string AllowAccessEmail {
            get {
                return ((string)(this["AllowAccessEmail"]));
            }
            set {
                this["AllowAccessEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@index=\'0\' and @text=\'Deny\']")]
        public string DenyAccessEmail {
            get {
                return ((string)(this["DenyAccessEmail"]));
            }
            set {
                this["DenyAccessEmail"] = value;
            }
        }
    }
}
