//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Auth {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AuthSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AuthSettings defaultInstance = ((AuthSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AuthSettings())));
        
        public static AuthSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'getStartedButton\')]")]
        public string GetStartedButton {
            get {
                return ((string)(this["GetStartedButton"]));
            }
            set {
                this["GetStartedButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("getStarted")]
        public string GetStartedLayout {
            get {
                return ((string)(this["GetStartedLayout"]));
            }
            set {
                this["GetStartedLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:4723/wd/hub")]
        public string AppiumServerURL {
            get {
                return ((string)(this["AppiumServerURL"]));
            }
            set {
                this["AppiumServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HT577SY03629")]
        public string HTCDesire626sDevice {
            get {
                return ((string)(this["HTCDesire626sDevice"]));
            }
            set {
                this["HTCDesire626sDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp")]
        public string ZonePackageName {
            get {
                return ((string)(this["ZonePackageName"]));
            }
            set {
                this["ZonePackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.InviteCode")]
        public string ZoneAppActivity {
            get {
                return ((string)(this["ZoneAppActivity"]));
            }
            set {
                this["ZoneAppActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.1")]
        public string HTCDesire626sVersionNumber {
            get {
                return ((string)(this["HTCDesire626sVersionNumber"]));
            }
            set {
                this["HTCDesire626sVersionNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.RelativeLayout[contains(@resource-id,\'img_container\')]")]
        public string ImageContainerValidation {
            get {
                return ((string)(this["ImageContainerValidation"]));
            }
            set {
                this["ImageContainerValidation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'phoneNumber\')]")]
        public string PhoneNumberField {
            get {
                return ((string)(this["PhoneNumberField"]));
            }
            set {
                this["PhoneNumberField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'password\')]")]
        public string PasswordField {
            get {
                return ((string)(this["PasswordField"]));
            }
            set {
                this["PasswordField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'verifyPassword\')]")]
        public string VerifyPasswordField {
            get {
                return ((string)(this["VerifyPasswordField"]));
            }
            set {
                this["VerifyPasswordField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[contains(@resource-id,\'have_an_acct\')]")]
        public string LoginTextPage {
            get {
                return ((string)(this["LoginTextPage"]));
            }
            set {
                this["LoginTextPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'proceed\')]")]
        public string ProceedButton {
            get {
                return ((string)(this["ProceedButton"]));
            }
            set {
                this["ProceedButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'invite_code\')]")]
        public string InviteCodeField {
            get {
                return ((string)(this["InviteCodeField"]));
            }
            set {
                this["InviteCodeField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'verifyInvite\')]")]
        public string VerifyInviteButton {
            get {
                return ((string)(this["VerifyInviteButton"]));
            }
            set {
                this["VerifyInviteButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'firstName\')]")]
        public string FirstNameField {
            get {
                return ((string)(this["FirstNameField"]));
            }
            set {
                this["FirstNameField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'lastName\')]")]
        public string LastNameField {
            get {
                return ((string)(this["LastNameField"]));
            }
            set {
                this["LastNameField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[contains(@resource-id,\'emailField\')]")]
        public string EmailField {
            get {
                return ((string)(this["EmailField"]));
            }
            set {
                this["EmailField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[contains(@resource-id,\'dob\')]")]
        public string DateOfBirthField {
            get {
                return ((string)(this["DateOfBirthField"]));
            }
            set {
                this["DateOfBirthField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[contains(@resource-id,\'gender\')]")]
        public string GenderField {
            get {
                return ((string)(this["GenderField"]));
            }
            set {
                this["GenderField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'signUp\')]")]
        public string SignUpButton {
            get {
                return ((string)(this["SignUpButton"]));
            }
            set {
                this["SignUpButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'date_picker_year\')]")]
        public string DatePickerYearButton {
            get {
                return ((string)(this["DatePickerYearButton"]));
            }
            set {
                this["DatePickerYearButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[contains(@resource-id,\'month_text_view\')]")]
        public string MonthTextView {
            get {
                return ((string)(this["MonthTextView"]));
            }
            set {
                this["MonthTextView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/done_button")]
        public string DoneButton {
            get {
                return ((string)(this["DoneButton"]));
            }
            set {
                this["DoneButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'positive\')]")]
        public string ReEnterPasswordButton {
            get {
                return ((string)(this["ReEnterPasswordButton"]));
            }
            set {
                this["ReEnterPasswordButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'negative\')]")]
        public string ForgotPasswordButton {
            get {
                return ((string)(this["ForgotPasswordButton"]));
            }
            set {
                this["ForgotPasswordButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[contains(@resource-id,\'spinner_item\')]")]
        public string GenderSelect {
            get {
                return ((string)(this["GenderSelect"]));
            }
            set {
                this["GenderSelect"] = value;
            }
        }
    }
}
