//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Ask {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AskSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AskSettings defaultInstance = ((AskSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AskSettings())));
        
        public static AskSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Ask\' and @index=\'0\']")]
        public string AskButton {
            get {
                return ((string)(this["AskButton"]));
            }
            set {
                this["AskButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter Total Amount\' and @index=\'1\']")]
        public string AskAmount {
            get {
                return ((string)(this["AskAmount"]));
            }
            set {
                this["AskAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter message and send picture\' and @index=\'1\']")]
        public string AskDescription {
            get {
                return ((string)(this["AskDescription"]));
            }
            set {
                this["AskDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'0\']")]
        public string AskAddImage {
            get {
                return ((string)(this["AskAddImage"]));
            }
            set {
                this["AskAddImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'ASK\' and @index=\'0\']")]
        public string AskButtonGo {
            get {
                return ((string)(this["AskButtonGo"]));
            }
            set {
                this["AskButtonGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\' and @text=\'Gallery\']")]
        public string SelectImageGallery {
            get {
                return ((string)(this["SelectImageGallery"]));
            }
            set {
                this["SelectImageGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.view.View[@index=\'0\']")]
        public string ImageViewGallery {
            get {
                return ((string)(this["ImageViewGallery"]));
            }
            set {
                this["ImageViewGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@content-desc=\'Ask n Receive GoLive\']")]
        public string AskFromInside {
            get {
                return ((string)(this["AskFromInside"]));
            }
            set {
                this["AskFromInside"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string GlobalContactList {
            get {
                return ((string)(this["GlobalContactList"]));
            }
            set {
                this["GlobalContactList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Ask\' and @index=\'1\']")]
        public string AskQuickLaunch {
            get {
                return ((string)(this["AskQuickLaunch"]));
            }
            set {
                this["AskQuickLaunch"] = value;
            }
        }
    }
}
