//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneAppTesting.Functional.Settings.Merchant {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MerchantSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MerchantSettings defaultInstance = ((MerchantSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MerchantSettings())));
        
        public static MerchantSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.appzonegroup.dejavuandroid.zoneRevamp:id/merchant_fab")]
        public string Merchant {
            get {
                return ((string)(this["Merchant"]));
            }
            set {
                this["Merchant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string SelectedMerchant {
            get {
                return ((string)(this["SelectedMerchant"]));
            }
            set {
                this["SelectedMerchant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\' and @text=\'Swift 4G Subscription\']")]
        public string SubscriptionButton {
            get {
                return ((string)(this["SubscriptionButton"]));
            }
            set {
                this["SubscriptionButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@index=\'1\' and @text=\'Enter Customer ID\']")]
        public string CustomerIDField {
            get {
                return ((string)(this["CustomerIDField"]));
            }
            set {
                this["CustomerIDField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.ImageView[@index=\'1\']")]
        public string PaymentItemSelect {
            get {
                return ((string)(this["PaymentItemSelect"]));
            }
            set {
                this["PaymentItemSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'0\']")]
        public string SelectedPaymentItem {
            get {
                return ((string)(this["SelectedPaymentItem"]));
            }
            set {
                this["SelectedPaymentItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Next\' and @index=\'0\']")]
        public string NextButton {
            get {
                return ((string)(this["NextButton"]));
            }
            set {
                this["NextButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.EditText[@text=\'Enter Amount\' and @index=\'1\']")]
        public string AmountField {
            get {
                return ((string)(this["AmountField"]));
            }
            set {
                this["AmountField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@text=\'Swift Services\' and @index=\'1\']")]
        public string TransactionSummary {
            get {
                return ((string)(this["TransactionSummary"]));
            }
            set {
                this["TransactionSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.Button[@text=\'Pay\' and @index=\'0\']")]
        public string PayButton {
            get {
                return ((string)(this["PayButton"]));
            }
            set {
                this["PayButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//android.widget.TextView[@index=\'1\']")]
        public string SummaryElements {
            get {
                return ((string)(this["SummaryElements"]));
            }
            set {
                this["SummaryElements"] = value;
            }
        }
    }
}
